from dotenv import dotenv_values
from pathlib import Path


BASE_PATH = Path(__file__).parent

ENV = dotenv_values(BASE_PATH / '.env')
BOOTSTRAP_SERVERS = ENV['BOOTSTRAP_SERVERS']    # must be comma-separated
TRIGGER_CODE_CHECK_NEW_TOPICS = ENV['TRIGGER_CODE_CHECK_NEW_TOPICS']
TRIGGER_CODE_LIST_TOPICS = ENV['TRIGGER_CODE_LIST_TOPICS']
TRIGGER_CODE_CLOSE = ENV['TRIGGER_CODE_CLOSE']
TRIGGER_CODE_FLUSH = ENV['TRIGGER_CODE_FLUSH']